### ISSUE TITLE
False positives - PrestaShop 8.01

### ISSUE THREAD

**Issue by Akumal78** [coreruleset/coreruleset#3117]
### Description
HI Does anyone have a whitelist to exclude false positives for prestashop 8.01?
Thanks

### Your Environment

* CRS version (e.g., v3.2.0): v3.3.4
* Paranoia level setting: 1
* ModSecurity version (e.g., 2.9.3): v2.9.7
* Web Server and version (e.g., apache 2.4.41): nginx/1.23.2
* Operating System and version: Ubuntu 20.04

### Confirmation

[ ] I have removed any personal data (email addresses, IP addresses,
    passwords, domain names) from any logs posted.

**Comment by azurit** [comment]
Hi, unfortunately, Prestashop is not currently supported. Would you mind sharing the logs? I can help you with writing of exclusion rules.

**Comment by Akumal78** [comment]
Hi @azurit thanks a lot, here are the false positives that I have detected so far:

##### id "920340 #######################
---R01qQdh8---B--
POST /admin/index.php/common/notifications?_token=xxxxxxx HTTP/2.0
referer: https://test.site.com/admin/index.php?controller=AdminStats&token=xxxxxxxxxxxxx
origin: 
x-requested-with: XMLHttpRequest
---R01qQdh8---H--
ModSecurity: Warning. Matched "Operator `Eq' with parameter `0' against variable `REQUEST_HEADERS:Content-Type' (Value: `0' ) [file "/etc/nginx/modsec/coreruleset-3.3.4/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf"] [line "688"] [id "**920340**"] [rev ""] [msg "Request Containing Content, but Missing Content-Type header"] [data ""] [severity "5"] [ver "OWASP_CRS/3.3.4"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-protocol"] [tag "paranoia-level/1"] [tag "OWASP_CRS"] [tag "capec/1000/210/272"] [hostname "x.x.x.x"] [uri "/admin/index.php/common/notifications"] [unique_id "167542436165.575529"] [ref "v693,1"]
###############################
########
POST /admin/index.php/common/notifications?_token=xxxxxxxxxxxxxxxxxxxxxxxxxxxxx HTTP/2.0
referer: https://test.site.com/admin/index.php?controller=AdminStats&token=xxxxxxxxxxxxxx
origin: https://test.site.com
---OPNu7PrM---H--
ModSecurity: Warning. Matched "Operator `Rx' with parameter `^\d+$' against variable `REQUEST_HEADERS:content-length' (Value: `0' ) [file "/etc/nginx/modsec/coreruleset-3.3.4/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf"] [line "128"] [id "**920160**"] [rev ""] [msg "Content-Length HTTP header is not numeric"] [data "0"] [severity "2"] [ver "OWASP_CRS/3.3.4"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-protocol"] [tag "paranoia-level/1"] [tag "OWASP_CRS"] [tag "capec/1000/210/272"] [hostname "x.x.x.x"] [uri "/admin/index.php/common/notifications"] [unique_id "167543072959.345665"] [ref "v693,1"]

ModSecurity: Warning. Matched "Operator `Rx' with parameter `^(?:(?:\*|[^\"(),\/:;<=>?![\x5c\]{}]+)\/(?:\*|[^\"(),\/:;<=>?![\x5c\]{}]+))(?:\s*+;\s*+(?:(?:charset\s*+=\s*+(?:\"?(?:iso-8859-15?|windows-1252|utf-8)\b\"?))|(?:(?:c(?:h(?:a(?:r(?:s(?:e[^t\"(),\/:;<=> (714 characters omitted)' against variable `REQUEST_HEADERS:accept' (Value: `application/json, text/javascript, */*; q=0.01' ) [file "/etc/nginx/modsec/coreruleset-3.3.4/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf"] [line "1147"] [id "**920600**"] [rev ""] [msg "Illegal Accept header: charset parameter"] [data "application/json, text/javascript, */*; q=0.01"] [severity "2"] [ver "OWASP_CRS/3.3.4"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-protocol"] [tag "paranoia-level/1"] [tag "OWASP_CRS"] [hostname "x.x.x.x"] [uri "/admin/index.php/common/notifications"] [unique_id "167543072959.345665"] [ref "v256,46t:lowercase"]

ModSecurity: Warning. Matched "Operator `Rx' with parameter `^(?i:(?:[a-z]{3,10}\s+(?:\w{3,7}?://[\w\-\./]*(?::\d+)?)?/[^?#]*(?:\?[^#\s]*)?(?:#[\S]*)?|connect (?:\d{1,3}\.){3}\d{1,3}\.?(?::\d+)?|options \*)\s+[\w\./]+|get /[^?#]*(?:\?[^#\s]*)?(?:#[\S]*)?)$' against variable `REQUEST_LINE' (Value: `POST /admin/index.php/common/notifications?_token=Zgym_Yz7--qaNQJdQp9rKW__mUi_nMD5HHgKs7Wo8Rc& (27 characters omitted)' ) [file "/etc/nginx/modsec/coreruleset-3.3.4/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf"] [line "48"] [id "**920100**"] [rev ""] [msg "Invalid HTTP Request Line"] [data "POST /admin/index.php/common/notifications?_token=Zgym_Yz7--qaNQJdQp9rKW__mUi_nMD5HHgKs7Wo8Rc&rand=1675430729757 HTTP/2.0"] [severity "4"] [ver "OWASP_CRS/3.3.4"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-protocol"] [tag "paranoia-level/1"] [tag "OWASP_CRS"] [tag "capec/1000/210/272"] [hostname "x.x.x.x"] [uri "/admin/index.php/common/notifications"] [unique_id "167543072959.345665"] [ref "v0,127"]

ModSecurity: Warning. Matched "Operator `Eq' with parameter `0' against variable `REQUEST_HEADERS:Content-Type' (Value: `0' ) [file "/etc/nginx/modsec/coreruleset-3.3.4/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf"] [line "688"] [id "**920340**"] [rev ""] [msg "Request Containing Content, but Missing Content-Type header"] [data ""] [severity "5"] [ver "OWASP_CRS/3.3.4"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-protocol"] [tag "paranoia-level/1"] [tag "OWASP_CRS"] [tag "capec/1000/210/272"] [hostname "x.x.x.x"] [uri "/admin/index.php/common/notifications"] [unique_id "167543072959.345665"] [ref "v693,1"]

ModSecurity: Warning. Matched "Operator `Ge' with parameter `5' against variable `TX:ANOMALY_SCORE' (Value: `15' ) [file "/etc/nginx/modsec/coreruleset-3.3.4/rules/REQUEST-949-BLOCKING-EVALUATION.conf"] [line "81"] [id "**949110**"] [rev ""] [msg "Inbound Anomaly Score Exceeded (Total Score: 15)"] [data ""] [severity "2"] [ver "OWASP_CRS/3.3.4"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-generic"] [hostname "x.x.x.x"] [uri "/admin/index.php/common/notifications"] [unique_id "167543072959.345665"] [ref ""]

##############


---AdrrK7u7---B--
GET /index.php?action=getAllWishlist&fc=module&module=blockwishlist&controller=action HTTP/2.0
host: test.site.com
sec-fetch-dest: empty
sec-fetch-mode: cors
cookie: xxxxx
accept: */*
te: trailers
accept-encoding: gzip, deflate, br
referer: https://test.site.com.it/index.php?controller=contact
sec-fetch-site: same-origin

---AdrrK7u7---H--
ModSecurity: Warning. Matched "Operator `Rx' with parameter `^(?:(?:\*|[^\"(),\/:;<=>?![\x5c\]{}]+)\/(?:\*|[^\"(),\/:;<=>?![\x5c\]{}]+))(?:\s*+;\s*+(?:(?:charset\s*+=\s*+(?:\"?(?:iso-8859-15?|windows-1252|utf-8)\b\"?))|(?:(?:c(?:h(?:a(?:r(?:s(?:e[^t\"(),\/:;<=> (714 characters omitted)' against variable `REQUEST_HEADERS:accept' (Value: `*/*' ) [file "/etc/nginx/modsec/coreruleset-3.3.4/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf"] [line "1147"] [id "**920600**"] [rev ""] [msg "Illegal Accept header: charset parameter"] [data "*/*"] [severity "2"] [ver "OWASP_CRS/3.3.4"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-protocol"] [tag "paranoia-level/1"] [tag "OWASP_CRS"] [hostname "x.x.x.x"] [uri "/index.php"] [unique_id "167542067034.723057"] [ref "v223,3t:lowercase"]

ModSecurity: Warning. Matched "Operator `Rx' with parameter `^(?i:(?:[a-z]{3,10}\s+(?:\w{3,7}?://[\w\-\./]*(?::\d+)?)?/[^?#]*(?:\?[^#\s]*)?(?:#[\S]*)?|connect (?:\d{1,3}\.){3}\d{1,3}\.?(?::\d+)?|options \*)\s+[\w\./]+|get /[^?#]*(?:\?[^#\s]*)?(?:#[\S]*)?)$' against variable `REQUEST_LINE' (Value: `GET /index.php?action=getAllWishlist&fc=module&module=blockwishlist&controller=action HTTP/2.0' ) [file "/etc/nginx/modsec/coreruleset-3.3.4/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf"] [line "48"] [id "**920100**"] [rev ""] [msg "Invalid HTTP Request Line"] [data "GET /index.php?action=getAllWishlist&fc=module&module=blockwishlist&controller=action HTTP/2.0"] [severity "4"] [ver "OWASP_CRS/3.3.4"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-protocol"] [tag "paranoia-level/1"] [tag "OWASP_CRS"] [tag "capec/1000/210/272"] [hostname "x.x.x.x"] [uri "/index.php"] [unique_id "167542067034.723057"] [ref "v0,94"]

ModSecurity: Warning. Matched "Operator `Ge' with parameter `5' against variable `TX:ANOMALY_SCORE' (Value: `8' ) [file "/etc/nginx/modsec/coreruleset-3.3.4/rules/REQUEST-949-BLOCKING-EVALUATION.conf"] [line "81"] [id "**949110**"] [rev ""] [msg "Inbound Anomaly Score Exceeded (Total Score: 8)"] [data ""] [severity "2"] [ver "OWASP_CRS/3.3.4"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-generic"] [hostname "x.x.x.x"] [uri "/index.php"] [unique_id "167542067034.723057"] [ref ""]

---m4eRgvjB---B--
GET /admin/themes/new-theme/public/6217402deed22f94057ff5f308c5a4b0.svg HTTP/2.0
referer: https://test.site.com/admin/themes/new-theme/public/theme.css
sec-fetch-site: same-origin
---m4eRgvjB---H--
ModSecurity: Warning. Matched "Operator `Rx' with parameter `^(?:(?:\*|[^\"(),\/:;<=>?![\x5c\]{}]+)\/(?:\*|[^\"(),\/:;<=>?![\x5c\]{}]+))(?:\s*+;\s*+(?:(?:charset\s*+=\s*+(?:\"?(?:iso-8859-15?|windows-1252|utf-8)\b\"?))|(?:(?:c(?:h(?:a(?:r(?:s(?:e[^t\"(),\/:;<=> (714 characters omitted)' against variable `REQUEST_HEADERS:accept' (Value: `image/avif,image/webp,*/*' ) [file "/etc/nginx/modsec/coreruleset-3.3.4/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf"] [line "1147"] [id "**920600**"] [rev ""] [msg "Illegal Accept header: charset parameter"] [data "image/avif,image/webp,*/*"] [severity "2"] [ver "OWASP_CRS/3.3.4"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-protocol"] [tag "paranoia-level/1"] [tag "OWASP_CRS"] [hostname "x.x.x.x"] [uri "/admin/themes/new-theme/public/6217402deed22f94057ff5f308c5a4b0.svg"] [unique_id "167543031198.386155"] [ref "v215,25t:lowercase"]

ModSecurity: Warning. Matched "Operator `Rx' with parameter `^(?i:(?:[a-z]{3,10}\s+(?:\w{3,7}?://[\w\-\./]*(?::\d+)?)?/[^?#]*(?:\?[^#\s]*)?(?:#[\S]*)?|connect (?:\d{1,3}\.){3}\d{1,3}\.?(?::\d+)?|options \*)\s+[\w\./]+|get /[^?#]*(?:\?[^#\s]*)?(?:#[\S]*)?)$' against variable `REQUEST_LINE' (Value: `GET /admin/themes/new-theme/public/6217402deed22f94057ff5f308c5a4b0.svg HTTP/2.0' ) [file "/etc/nginx/modsec/coreruleset-3.3.4/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf"] [line "48"] [id "**920100**"] [rev ""] [msg "Invalid HTTP Request Line"] [data "GET /admin/themes/new-theme/public/6217402deed22f94057ff5f308c5a4b0.svg HTTP/2.0"] [severity "4"] [ver "OWASP_CRS/3.3.4"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-protocol"] [tag "paranoia-level/1"] [tag "OWASP_CRS"] [tag "capec/1000/210/272"] [hostname "x.x.x.x"] [uri "/admin/themes/new-theme/public/6217402deed22f94057ff5f308c5a4b0.svg"] [unique_id "167543031198.386155"] [ref "v0,86"]

ModSecurity: Warning. Matched "Operator `Ge' with parameter `5' against variable `TX:ANOMALY_SCORE' (Value: `8' ) [file "/etc/nginx/modsec/coreruleset-3.3.4/rules/REQUEST-949-BLOCKING-EVALUATION.conf"] [line "81"] [id "**949110**"] [rev ""] [msg "Inbound Anomaly Score Exceeded (Total Score: 8)"] [data ""] [severity "2"] [ver "OWASP_CRS/3.3.4"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-generic"] [hostname "x.x.x.x"] [uri "/admin/themes/new-theme/public/6217402deed22f94057ff5f308c5a4b0.svg"] [unique_id "167543031198.386155"] [ref ""]

**Comment by azurit** [comment]
@Akumal78 These does not seems to be false positives, just look at the error messages, all of them are simply invalid requests:
 - Request Containing Content, but Missing Content-Type header
 - Invalid HTTP Request Line
 - Illegal Accept header: charset parameter

**Comment by Akumal78** [comment]
To solve the problem using Prestashop should I remove these Rules from control?

SecRuleRemoveById 949110
SecRuleRemoveById 920600
SecRuleRemoveById 920100
SecRuleRemoveById 920160
SecRuleRemoveById 920470
SecRuleRemoveById 920340

**Comment by dune73** [comment]
The requests reported do not align with the rules triggered. I do not see an Invalid HTTP request line for example. At least not at first sight.

I wonder whether this has to do with using HTTP/2.0.

@Akumal78 : That would do the trick, but I think there is something else going on here and you might be tuning away the wrong rules or as @azurit suggests real attacks.

**Comment by azurit** [comment]
@dune73 I'm using modsec + CRS with HTTP/2 without any problems, so it's not this case.

@Akumal78 Are you sure these are false positives?

**Comment by Akumal78** [comment]
This is a new Prestashop installation, I haven't made any changes yet. Does this mean that Prestashop doesn't care about OWASP rules?

**Comment by Akumal78** [comment]
The site hasn't been published yet, the IPs are inside the lan. Prestashop is issuing its own HTTP requests, I think these warnings are all false positive because it's a brand new installation

**Comment by azurit** [comment]
@Akumal78 Sorry but your logs looks weird:
 - there is no User-Agent header
 - i can see invalid header `te: trailers`
 - i can see invalid `Accept` header: `accept: /`
 - one request is missing `Host` header

These are not false positives. Logged requests are simply invalid.

**Comment by Akumal78** [comment]
@azurit Sorry for misunderstanding, below the complete log of the home page site

---a9N5MI93---A--
[03/Feb/2023:17:20:17 +0100] 16754412170.227274 x.x.x.x 49474 x.x.x.x 443
---a9N5MI93---B--
GET /index.php?action=getAllWishlist&fc=module&module=blockwishlist&controller=action HTTP/2.0
accept-encoding: gzip, deflate, br
cookie: PrestaShop-xxxxxx
referer: https://test.site.com/index.php
sec-ch-ua-platform: "Windows"
sec-fetch-site: same-origin
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
sec-ch-ua-mobile: ?0
accept: */*
sec-ch-ua: "Not_A Brand";v="99", "Google Chrome";v="109", "Chromium";v="109"
sec-fetch-dest: empty
sec-fetch-mode: cors
host: test.site.com
accept-language: it-IT,it;q=0.9,en-US;q=0.8,en;q=0.7,fr;q=0.6,pt;q=0.5

---a9N5MI93---E--
{"success":false,"message":"xxxxxxxxx"}

---a9N5MI93---F--
HTTP/2.0 200
Server:
Server:
Date: Fri, 03 Feb 2023 16:20:17 GMT
Content-Type: text/html; charset=utf-8
Connection: close
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Strict-Transport-Security: max-age=31536000

---a9N5MI93---H--
ModSecurity: Warning. Matched "Operator `Rx' with parameter `^(?:(?:\*|[^\"(),\/:;<=>?![\x5c\]{}]+)\/(?:\*|[^\"(),\/:;<=>?![\x5c\]{}]+))(?:\s*+;\s*+(?:(?:charset\s*+=\s*+(?:\"?(?:iso-8859-15?|windows-1252|utf-8)\b\"?))|(?:(?:c(?:h(?:a(?:r(?:s(?:e[^t\"(),\/:;<=> (714 characters omitted)' against variable `REQUEST_HEADERS:accept' (Value: `*/*' ) [file "/etc/nginx/modsec/coreruleset-3.3.4/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf"] [line "1147"] [id "920600"] [rev ""] [msg "Illegal Accept header: charset parameter"] [data "*/*"] [severity "2"] [ver "OWASP_CRS/3.3.4"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-protocol"] [tag "paranoia-level/1"] [tag "OWASP_CRS"] [hostname "x.x.x.x"] [uri "/index.php"] [unique_id "16754412170.227274"] [ref "v382,3t:lowercase"]

ModSecurity: Warning. Matched "Operator `Rx' with parameter `^(?i:(?:[a-z]{3,10}\s+(?:\w{3,7}?://[\w\-\./]*(?::\d+)?)?/[^?#]*(?:\?[^#\s]*)?(?:#[\S]*)?|connect (?:\d{1,3}\.){3}\d{1,3}\.?(?::\d+)?|options \*)\s+[\w\./]+|get /[^?#]*(?:\?[^#\s]*)?(?:#[\S]*)?)$' against variable `REQUEST_LINE' (Value: `GET /index.php?action=getAllWishlist&fc=module&module=blockwishlist&controller=action HTTP/2.0' ) [file "/etc/nginx/modsec/coreruleset-3.3.4/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf"] [line "48"] [id "920100"] [rev ""] [msg "Invalid HTTP Request Line"] [data "GET /index.php?action=getAllWishlist&fc=module&module=blockwishlist&controller=action HTTP/2.0"] [severity "4"] [ver "OWASP_CRS/3.3.4"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-protocol"] [tag "paranoia-level/1"] [tag "OWASP_CRS"] [tag "capec/1000/210/272"] [hostname "x.x.x.x"] [uri "/index.php"] [unique_id "16754412170.227274"] [ref "v0,94"]

ModSecurity: Warning. Matched "Operator `Ge' with parameter `5' against variable `TX:ANOMALY_SCORE' (Value: `8' ) [file "/etc/nginx/modsec/coreruleset-3.3.4/rules/REQUEST-949-BLOCKING-EVALUATION.conf"] [line "81"] [id "949110"] [rev ""] [msg "Inbound Anomaly Score Exceeded (Total Score: 8)"] [data ""] [severity "2"] [ver "OWASP_CRS/3.3.4"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-generic"] [hostname "x.x.x.x"] [uri "/index.php"] [unique_id "16754412170.227274"] [ref ""]

---a9N5MI93---J--

---a9N5MI93---K--

---a9N5MI93---Z--

**Comment by azurit** [comment]
Can you copy&paste rules `920100` and `920600` from your CRS installation?

**Comment by Akumal78** [comment]
SecRule REQUEST_LINE "!@rx ^(?i:(?:[a-z]{3,10}\s+(?:\w{3,7}?://[\w\-\./]*(?::\d+)?)?/[^?#]*(?:\?[^#\s]*)?(?:#[\S]*)?|connect (?:\d{1,3}\.){3}\d{1,3}\.?(?::\d+)?|options \*)\s+[\w\./]+|get /[^?#]*(?:\?[^#\s]*)?(?:#[\S]*)?)$" \
    "id:920100,\
    phase:2,\
    block,\
    t:none,\
    msg:'Invalid HTTP Request Line',\
    logdata:'%{request_line}',\
    tag:'application-multi',\
    tag:'language-multi',\
    tag:'platform-multi',\
    tag:'attack-protocol',\
    tag:'paranoia-level/1',\
    tag:'OWASP_CRS',\
    tag:'capec/1000/210/272',\
    ver:'OWASP_CRS/3.3.4',\
    severity:'WARNING',\
    setvar:'tx.anomaly_score_pl1=+%{tx.warning_anomaly_score}'"


SecRule REQUEST_HEADERS:Accept "!@rx ^(?:(?:\*|[^\"(),\/:;<=>?![\x5c\]{}]+)\/(?:\*|[^\"(),\/:;<=>?![\x5c\]{}]+))(?:\s*+;\s*+(?:(?:charset\s*+=\s*+(?:\"?(?:iso-8859-15?|windows-1252|utf-8)\b\"?))|(?:(?:c(?:h(?:a(?:r(?:s(?:e[^t\"(),\/:;<=>?![\x5c\]{}]|[^e\"(),/:;<=>?![\x5c\]{}])|[^s\"(),/:;<=>?![\x5c\]{}])|[^r\"(),/:;<=>?![\x5c\]{}])|[^a\"(),/:;<=>?![\x5c\]{}])|[^h\"(),/:;<=>?![\x5c\]{}])|[^c\"(),/:;<=>?![\x5c\]{}])[^\"(),/:;<=>?![\x5c\]{}]*(?:)\s*+=\s*+[^(),/:;<=>?![\x5c\]{}]+)|;?))*(?:\s*+,\s*+(?:(?:\*|[^\"(),\/:;<=>?![\x5c\]{}]+)\/(?:\*|[^\"(),\/:;<=>?![\x5c\]{}]+))(?:\s*+;\s*+(?:(?:charset\s*+=\s*+(?:\"?(?:iso-8859-15?|windows-1252|utf-8)\b\"?))|(?:(?:c(?:h(?:a(?:r(?:s(?:e[^t\"(),\/:;<=>?![\x5c\]{}]|[^e\"(),/:;<=>?![\x5c\]{}])|[^s\"(),/:;<=>?![\x5c\]{}])|[^r\"(),/:;<=>?![\x5c\]{}])|[^a\"(),/:;<=>?![\x5c\]{}])|[^h\"(),/:;<=>?![\x5c\]{}])|[^c\"(),/:;<=>?![\x5c\]{}])[^\"(),/:;<=>?![\x5c\]{}]*(?:)\s*+=\s*+[^(),/:;<=>?![\x5c\]{}]+)|;?))*)*$" \
    "id:920600,\
    phase:1,\
    block,\
    t:none,t:lowercase,\
    msg:'Illegal Accept header: charset parameter',\
    logdata:'%{MATCHED_VAR}',\
    tag:'application-multi',\
    tag:'language-multi',\
    tag:'platform-multi',\
    tag:'attack-protocol',\
    tag:'paranoia-level/1',\
    tag:'OWASP_CRS',\
    ver:'OWASP_CRS/3.3.4',\
    severity:'CRITICAL',\
    setvar:'tx.anomaly_score_pl1=+%{tx.critical_anomaly_score}'"

**Comment by azurit** [comment]
@dune73 What do you think about these error messages?
`ModSecurity: Warning. Matched "Operator 'Rx' with parameter ... against variable ...`

I cannot get such errors using my installation. If `@rx` is used, i'm getting errors like this:
`ModSecurity: Warning. Pattern match ... at ...`
`ModSecurity: Warning. Match of ... against ... required`

**Comment by RedXanadu** [comment]
@azurit I think that's ModSecurity v2 vs v3 logging slightly differently.

@Akumal78 Can you confirm which engine you're using? You stated in your opening message that you're using ModSecurity v2 with Nginx: can you confirm? Or are you using ModSecurity v3 with Nginx?

**Comment by Akumal78** [comment]
@RedXanadu yes, sorry is ModSecurity v3 with Nginx

**Comment by azurit** [comment]
@Akumal78 Can you try ModSecurity v2?

**Comment by Akumal78** [comment]
do i have to uninstall nginix to install modsecurity v2? Do you have a procedure?

**Comment by RedXanadu** [comment]
Okay: I've had time to take a proper look at this report. What you've reported @Akumal78 looks very, very broken indeed:

``
Matched "Operator `Rx' with parameter `^\d+$' against variable `REQUEST_HEADERS:content-length'
``
``
(Value: `0' )…[id "920160"] [rev ""] [msg "Content-Length HTTP header is not numeric"]…
``

Clearly the value `0` is numeric! The regular expression `^\d+$` should match against `0` which should mean that rule 920160 is *not* triggered.

This sounds very much like some problems we saw from a few users a couple of months ago, where regular expressions were simply being incorrectly evaluated: _just plain wrong_, like in your example here. *(References: #2752, #2976).*

All of the previous reports were from Nginx users, like yourself. In the end the problems were fixed. The problem was either due to a bad Nginx build / bad module build (they were using some weird third party sources we had never heard of) **or** potentially due to using an Nginx Lua module.

---

**Question 1:** Where did you get your Nginx build from?

**Question 2:** Are you loading a Lua module into Nginx?

**Comment by azurit** [comment]
For me, it looks like that nginx is ignoring a `!` before `@rx`.

**Comment by Akumal78** [comment]
@RedXanadu 
Question 1: from ppa:ondrej/nginx-stable -y add-apt-repository ppa:ondrej/nginx -y
Question 2: Yes, I see in my nginx modules-enabled -> 50-mod-http-lua.conf -> /usr/share/nginx/modules-available/mod-http-lua.conf
How can I solve the problem?

**Comment by Akumal78** [comment]
@RedXanadu I have disable the Nginx Lua module but not solved the problem
Thanks for all information

**Comment by Akumal78** [comment]
Hi at all i have reinstall nginix from official Nginx stable repository, and now i don't have more warning in modsecurity log
Thanks

**Comment by RedXanadu** [comment]
That's great news @Akumal78! Thanks for reporting back and closing off the issue :smile:

**Comment by blackmold9** [comment]
Everything functions correctly after using https://modsecurity.digitalwave.hu/ to build nginx

**Comment by blackmold9** [comment]
After building nginx from https://modsecurity.digitalwave.hu/, everything functions correctly

**Comment by oerdnj** [comment]
@Akumal78 If you have a room for an experiment then please make sure that you compile ModSecurity with PCRE2 (`--with-pcre2`) and only PCRE2, and then retest with `ppa:ondrej/nginx` again.
